### ISSUE TITLE
MITM Proxy 502 Bad Gateway Due to Certificate

### ISSUE THREAD

**Issue by MichaelBone** [planningalerts-scrapers/town_of_gawler_sa_development_applications#1]
With the latest update to the MITM proxy a lot of TLS/SSL errors that were occurring are now fixed.  However this one scraper is now erroring due to a problem with certificates  **"unable to get local issuer certificate"** (for example, maybe the Town of Gawler web site is using a self signed certificate):

```
Retrieving page: https://eservices.gawler.sa.gov.au/eservice/daEnquiryInit.do?doc_typ=4&nodeNum=3228
{ StatusCodeError: 502 - "<html>\n            <head>\n                <title>502 Bad Gateway</title>\n            </head>\n            <body>\n            <h1>502 Bad Gateway</h1>\n            <p>Certificate verification error for eservices.gawler.sa.gov.au: unable to get local issuer certificate (errno: 20, depth: 0)</p>\n            </body>\n        </html>"
    at new StatusCodeError (/app/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/app/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/app/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/app/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/app/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
```

A possible solution is to use a proxy server (ie. the same workaround that was used previously for the scrapers that were encountering TLS/SSL errors).

**Comment by jamezpolley** [comment]
Looking into this, I think mitmproxy is doing the right thing.

The certificate chain that Gawler's web server is returning is incomplete:

````
Certificate chain                                                                                                                                                                                                                                                              0 s:C = AU, ST = South Australia, L = Gawler East, O = Town of Gawler, OU = IT, CN = *.gawler.sa.gov.au                                                                                                                                                                         
   i:C = US, O = DigiCert Inc, OU = www.digicert.com, CN = GeoTrust RSA CA 2018
````

There should be two more certificates: the intermediate GeoTrust cert and the root DigiCert cert. The latter is in the debian default set, but the former is not; mitmproxy can't generate a complete chain back to a trusted cert, so it's returning an error.

I'm wondering if there's a debian package somewhere that has a bigger set of the intermediate certs...

**Comment by jamezpolley** [comment]
@MichaelBone Is there any chance we could approach the council to ask them to fix their web server?

@mlandauer We could fix this by adding the missing intermediate CA cert into the mitmproxy docker image at build time. Do you have any thoughts on whether this is something we want to do?

I'd be annoyed if it was something we had to do too much of, but I think it should be a once-off task to add the cert into the git repo and update the Dockerfile to fold it in at build time. The only ongoing maintenance issue I can think of is that we'd probably want to be tracking if that cert ever gets revoked...

I'm weighing up "We want to provide usefulness to the residents of Gawler so we'll work around their council's broken server" vs "We want to provide maximum service to maximum people so we're not going to do random bits of work to correct for every broken server"..
